import { Service } from '@/types';

export const services: Service[] = [
  {
    id: 'location-stands',
    nom: 'Location de Stands',
    description: 'Mise à disposition de stands professionnels pour congrès médicaux, salons et événements scientifiques.',
    icone: 'Building2',
    details: [
      'Large gamme de stands modernes et modulables',
      'Matériel conforme aux standards internationaux',
      'Disponibilité immédiate pour vos événements',
      'Options de personnalisation (branding, couleurs)',
      'Équipements technologiques intégrés',
      'Stands adaptés à tous les budgets',
      'Contrats flexibles (1 jour à plusieurs semaines)',
    ],
  },
  {
    id: 'installation-demontage',
    nom: 'Installation et Démontage',
    description: 'Service complet d\'installation professionnelle avant votre événement et démontage après.',
    icone: 'Wrench',
    details: [
      'Équipe technique qualifiée et expérimentée',
      'Installation rapide et soignée',
      'Respect des horaires et contraintes du site',
      'Montage selon plan d\'implantation',
      'Vérification complète avant ouverture',
      'Démontage rapide en fin d\'événement',
      'Nettoyage du site',
      'Présence possible pendant l\'événement',
    ],
  },
  {
    id: 'logistique',
    nom: 'Service Logistique',
    description: 'Gestion complète de la logistique : transport, stockage, et manutention de vos stands.',
    icone: 'Truck',
    details: [
      'Transport sécurisé du matériel',
      'Livraison ponctuelle sur site',
      'Gestion des accès et autorisations',
      'Stockage sécurisé entre événements',
      'Assurance du matériel incluse',
      'Coordination avec les organisateurs',
      'Service de manutention professionnel',
    ],
  },
  {
    id: 'conseil-exposition',
    nom: 'Conseils pour l\'Exposition',
    description: 'Accompagnement personnalisé pour optimiser votre présence et maximiser votre impact.',
    icone: 'Lightbulb',
    details: [
      'Analyse de vos besoins et objectifs',
      'Recommandations sur le choix du stand',
      'Conseils d\'aménagement et décoration',
      'Optimisation de l\'espace disponible',
      'Suggestions pour attirer les visiteurs',
      'Aide à la planification logistique',
      'Support pour l\'implantation des équipements',
    ],
  },
  {
    id: 'assistance-technique',
    nom: 'Assistance Technique',
    description: 'Support technique pendant toute la durée de votre événement pour garantir un déroulement parfait.',
    icone: 'Headphones',
    details: [
      'Technicien disponible pendant l\'événement',
      'Intervention rapide en cas de besoin',
      'Assistance pour les équipements audiovisuels',
      'Résolution des problèmes techniques',
      'Support pour modifications de dernière minute',
      'Hotline disponible 7j/7',
      'Maintenance préventive',
    ],
  },
  {
    id: 'personnalisation',
    nom: 'Personnalisation et Branding',
    description: 'Customisation complète de votre stand aux couleurs et à l\'image de votre marque.',
    icone: 'Palette',
    details: [
      'Application de votre identité visuelle',
      'Impression grand format haute qualité',
      'Signalétique personnalisée',
      'Habillage complet du stand',
      'Intégration de votre logo et messages',
      'Création de supports visuels',
      'Conseil en communication visuelle',
    ],
  },
];

